"""create incidents table

Revision ID: 8c91f6d86039
Revises: 
Create Date: 2026-07-10 22:38:23.690107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c91f6d86039'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('github_repo_url', sa.Text(), nullable=False),
    sa.Column('reported_at', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('incident_type', sa.String(length=30), nullable=True),
    sa.Column('affected_services', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('investigation_window', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('analysis_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    # ### end Alembic commands ###
