"""add organisation_id to existing tables

Revision ID: b563f067332d
Revises: a6a50c5199e1
Create Date: 2026-07-14 16:00:43.837910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b563f067332d'
down_revision: Union[str, None] = 'a6a50c5199e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('organisation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_agent_runs_organisation_id'), 'agent_runs', ['organisation_id'], unique=False)
    op.create_foreign_key(None, 'agent_runs', 'organisations', ['organisation_id'], ['id'])
    op.add_column('feedback', sa.Column('organisation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_feedback_organisation_id'), 'feedback', ['organisation_id'], unique=False)
    op.create_foreign_key(None, 'feedback', 'organisations', ['organisation_id'], ['id'])
    op.add_column('incidents', sa.Column('organisation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_incidents_organisation_id'), 'incidents', ['organisation_id'], unique=False)
    op.create_foreign_key(None, 'incidents', 'organisations', ['organisation_id'], ['id'])
    op.add_column('rca_reports', sa.Column('organisation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rca_reports_organisation_id'), 'rca_reports', ['organisation_id'], unique=False)
    op.create_foreign_key(None, 'rca_reports', 'organisations', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rca_reports', type_='foreignkey')
    op.drop_index(op.f('ix_rca_reports_organisation_id'), table_name='rca_reports')
    op.drop_column('rca_reports', 'organisation_id')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_index(op.f('ix_incidents_organisation_id'), table_name='incidents')
    op.drop_column('incidents', 'organisation_id')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_organisation_id'), table_name='feedback')
    op.drop_column('feedback', 'organisation_id')
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.drop_index(op.f('ix_agent_runs_organisation_id'), table_name='agent_runs')
    op.drop_column('agent_runs', 'organisation_id')
    # ### end Alembic commands ###
