"""create rca_reports table

Revision ID: fcc4ac79a589
Revises: 77e3ab9bb5f9
Create Date: 2026-07-11 00:58:31.302352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcc4ac79a589'
down_revision: Union[str, None] = '77e3ab9bb5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rca_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prevention_note', sa.Text(), nullable=True),
    sa.Column('raw_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.String(length=50), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rca_reports')
    # ### end Alembic commands ###
