services:

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: incidentiq-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:11.1.0
    container_name: incidentiq-grafana

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

    depends_on:
      - prometheus

volumes:
  grafana-data: